### ISSUE TITLE
No "show-instructions.vbs" handling

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/bzs-config-utility#57]
On it.

**Comment by theVKC** [comment]
Tied to #36.

**Comment by heatherallen** [comment]
I'm still getting an error message when clicking on "About the BlueZone Scripts". Error box states, "Script Error at Line 1, Column 1

**Comment by theVKC** [comment]
Did you reinstall @heatherallen? Did you extract the files to your directory and so forth?

**Comment by heatherallen** [comment]
@theVKC , yes I did.  All other buttons are working now that you had us test except that one.

**Comment by theVKC** [comment]
Hmmmm. Do you have a "show-instructions.vbs" inside your locally-installed-files folder?

**Comment by heatherallen** [comment]
yes I do.

**Comment by theVKC** [comment]
Good deal. Can you copy the contents of it into a text file and then send it to me?

**Comment by theVKC** [comment]
(via email, obvs)

**Comment by heatherallen** [comment]
I'm guessing you are wanting a copy of all files in my locally-installed-files folder? or just the "show-instructions".vbs?

**Comment by theVKC** [comment]
Just the show-instructions file. Also, can you confirm it was also in the zipped folder? Just want to make sure the installer created it.

**Comment by heatherallen** [comment]
yes it came over in the zipped folder and I will email you the text file of that vbs

**Comment by khiestand** [comment]
@theVKC I am getting an error message too after re-installing

**Comment by theVKC** [comment]
@khiestand: wondering if you did the same thing Heather is investigating. Can you confirm your installation directory? Did it include two "locally-installed-files" directories?

**Comment by WCMattAnderson** [comment]
@theVKC @khiestand Our full script path for Wright is at C:\ProgramData\BlueZone\Scripts\Child Support Scripts\locally-installed-files

**Comment by theVKC** [comment]
Thanks @WCMattAnderson! Can you tell me the path indicated in the show-instructions.vbs file? Wondering if I have something recursive going on in it.

**Comment by WCMattAnderson** [comment]
CreateObject("WScript.Shell").Run("C:\ProgramData\BlueZone\Scripts\Child Support Scripts\locally-installed-files\instructions.html") 
 See attached image for full location of scripts and attempt at manual VBS run.
![full](https://cloud.githubusercontent.com/assets/23243495/19977378/5bc68bd4-a1c1-11e6-9aa5-30668ee5c8bf.png)

**Comment by theVKC** [comment]
@WCMattAnderson: this seems quite bizarre. This is essentially the exact process I've tested. The path looks identical. What happens when you copy the above path into a browser?

**Comment by WCMattAnderson** [comment]
I did test C:\ProgramData\BlueZone\Scripts\Child Support Scripts\locally-installed-files\instructions.html and it works as expected opening the informational page.

I changed the script file to CreateObject("WScript.Shell").Run("https://www.google.com/?gws_rd=ssl") and it works correctly running the VB.

Also tested removing the spaces as of the folder name and that works correctly as well.
CreateObject("WScript.Shell").Run("c:\ProgramData\BlueZone\Scripts\Child-Support-Scripts\locally-installed-files\instructions.html") 

Changing folder name and VB back with spaces results in the error again.

**Comment by theVKC** [comment]
Hmmmm. Do you think the problem could be the spaces in the file name then, @WCMattAnderson? Would you suggest my installer should remove spaces? This could explain why my local version isn't broken, because my path has no spaces.

**Comment by WCMattAnderson** [comment]
Correct, but we would not know what Counties decide to use spaces in the file path, as we have ours under Child Support Scripts. This is working correctly for us as a suggestion:

CreateObject("WScript.Shell").Run("""c:\ProgramData\BlueZone\Scripts\Child Support Scripts\locally-installed-files\instructions.html""")

**Comment by theVKC** [comment]
Yup. And it makes sense because it passes the quotes as a parameter. I can pretty easily repeat the process. Boom! Thank you for your help!

**Comment by theVKC** [comment]
@heatherallen has confirmed the new process worked. @WCMattAnderson: not sure if you're planning on reinstalling, but I've implemented three quotes around the path, and my tests with various file paths seem to be working.

Because @heatherallen has confirmed independently, I'm closing the issue. Go team!
