### ISSUE TITLE
Require Array Lists for Judges, Magistrates, & Attorneys to contain at least one item

### ISSUE THREAD

**Issue by WCMattAnderson** [MN-Script-Team/bzs-config-utility#68]
'An array of county judges. "Select one:" should ALWAYS be in there, and ALWAYS be first. Replace "County judge #" with your agency's county attorney names.
county_attorney_array = array("Karen Wolff", "Terry Frazier")

'An array of child support magistrates. "Select one:" should ALWAYS be in there, and ALWAYS be first.  Replace "Magistrate # with your agency's child support magistrate names.
child_support_magistrates_array = array()

'An array of judges. "Select one:" should ALWAYS be in there, and ALWAYS be first.  Replace "Judge #" with your agency's judges names.
county_judge_array = array()

Reading the notes I assume this is a drop down list and the first selection IF the input isn't NULL then it needs to append a "Select one:" option before any items listed in the installer.

**Comment by theVKC** [comment]
I believe the individual scripts using this append this "select one" to all choices. Do you have an instance of it not doing that? Did someone not add magistrates and judges when installing?

**Comment by WCMattAnderson** [comment]
We added our users after the fact, I manually added the "select one" to all options assuming it was an error. I do not have PRISM access to actually test these but can only assume from the code. A fresh download now reports these without the select one:

'An array of county judges. "Select one:" should ALWAYS be in there, and ALWAYS be first. Replace "County judge #" with your agency's county attorney names.
county_attorney_array = array("test1", "test2")

'An array of child support magistrates. "Select one:" should ALWAYS be in there, and ALWAYS be first.  Replace "Magistrate # with your agency's child support magistrate names.
child_support_magistrates_array = array("test1", "test2")

'An array of judges. "Select one:" should ALWAYS be in there, and ALWAYS be first.  Replace "Judge #" with your agency's judges names.
county_judge_array = array("test1", "test2")

**Comment by theVKC** [comment]
I think the actual script does, in fact, add it in. Clearly the comments above the code are old! It used to be required but I removed it some time ago. I should go through and update the comments.

**Comment by theVKC** [comment]
See #69. Now, I'm thinking that I should require at least one attorney, magistrate, and judge for each agency. On it.

**Comment by theVKC** [comment]
With Python conversion, this issue is no longer necessary. Closing.
